// do zrobienia obsługa w node.js
const offerArr = [
    {
        position: 'Front-end developer',
        tech: 'React',
        salaryFrom: 5000,
        salaryTo: 10000,
        city: 'Kraków',
        experience: 2,
        id: 1,
    },
    {
        position: 'Back-end developer',
        tech: 'Java',
        salaryFrom: 6500,
        salaryTo: 11000,
        city: 'Kraków',
        experience: 2.5,
        id: 2,
    },
    {
        position: 'DevOps Engineer',
        tech: 'Linux',
        salaryFrom: 8000,
        salaryTo: 14000,
        city: 'Kraków',
        experience: 3,
        id: 3,
    },
    {
        position: 'UX/UI designer',
        tech: 'Sketch',
        salaryFrom: 4500,
        salaryTo: 7800,
        city: 'Kraków',
        experience: 1,
        id: 4,
    },
    {
        position: 'Project Manager',
        tech: 'PM',
        salaryFrom: 8000,
        salaryTo: 15000,
        city: 'Kraków',
        experience: 3,
        id: 5,
    },
    {
        position: 'QA Tester',
        tech: 'Java',
        salaryFrom: 6000,
        salaryTo: 90000,
        city: 'Kraków',
        experience: 1.5,
        id: 6,
    },
    {
        position: 'Back-end developer',
        tech: 'Java',
        salaryFrom: 6500,
        salaryTo: 11000,
        city: 'Kraków',
        experience: 2.5,
        id: 7,
    },
    {
        position: 'DevOps Engineer',
        tech: 'Java',
        salaryFrom: 8000,
        salaryTo: 14000,
        city: 'Kraków',
        experience: 3,
        id: 8,
    },
    {
        position: 'UX/UI designer',
        tech: 'Java',
        salaryFrom: 4500,
        salaryTo: 7800,
        city: 'Kraków',
        experience: 1,
        id: 9,
    },
    {
        position: 'Project Manager',
        tech: 'Java',
        salaryFrom: 8000,
        salaryTo: 15000,
        city: 'Kraków',
        experience: 3,
        id: 10,
    },
    {
        position: 'QA Tester',
        tech: 'Angular',
        salaryFrom: 6000,
        salaryTo: 90000,
        city: 'Kraków',
        experience: 1.5,
        id: 11,
    },
    {
        position: 'Back-end developer',
        tech: 'Angular',
        salaryFrom: 6500,
        salaryTo: 11000,
        city: 'Kraków',
        experience: 2.5,
        id: 12,
    },
    {
        position: 'DevOps Engineer',
        tech: 'Angular',
        salaryFrom: 8000,
        salaryTo: 14000,
        city: 'Kraków',
        experience: 3,
        id: 13,
    },
    {
        position: 'UX/UI designer',
        tech: 'Vue',
        salaryFrom: 4500,
        salaryTo: 7800,
        city: 'Kraków',
        experience: 1,
        id: 14,
    },
    {
        position: 'Project Manager',
        tech: 'Vue',
        salaryFrom: 8000,
        salaryTo: 15000,
        city: 'Kraków',
        experience: 3,
        id: 15,
    },
    {
        position: 'QA Tester',
        tech: 'Vue',
        salaryFrom: 6000,
        salaryTo: 90000,
        city: 'Kraków',
        experience: 1.5,
        id: 16,
    },
    {
        position: 'UX/UI designer',
        tech: 'Vue',
        salaryFrom: 4500,
        salaryTo: 7800,
        city: 'Kraków',
        experience: 1,
        id: 17,
    },
    {
        position: 'Project Manager',
        tech: 'React',
        salaryFrom: 8000,
        salaryTo: 15000,
        city: 'Kraków',
        experience: 3,
        id: 18,
    },
    {
        position: 'QA Tester',
        tech: 'React',
        salaryFrom: 6000,
        salaryTo: 90000,
        city: 'Kraków',
        experience: 1.5,
        id: 19,
    },
    {
        position: 'Project Manager',
        tech: 'React',
        salaryFrom: 8000,
        salaryTo: 15000,
        city: 'Kraków',
        experience: 3,
        id: 20,
    },
]

export { offerArr }
